export const ADD_CITY = "ADD_CITY"
export const DELETE_CITY = "DELETE_CITY"

export const GET_CITY_LIST = "GET_CITY_LIST"
export const SET_NEXT_CITY_NAME = "SET_NEXT_CITY_NAME"

export const FETCH_SUGGESTIONS = "FETCH_SUGGESTIONS"
export const SET_SUGGESTION_LIST = "SET_SUGGESTION_LIST"

export const SET_TEMPERATURE_FILTER = "SET_TEMPERATURE_FILTER"

export const ADD_CITY_WITH_WEATHER = "ADD_CITY_WITH_WEATHER"
export const ADD_WEATHER_TO_CITY = "ADD_WEATHER_TO_CITY"
